AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: To run datomic in my free tier ec2 image.

Resources:


Resources:
  AppNode:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-da5110cc
      KeyName: aws-key1
      SecurityGroups:
        - !Ref AppNodeSG
      UserData: !Base64 |
        #!/bin/bash
        exec > >(tee \/var\/log\/user-data.log|logger -t user-data -s 2>\/dev\/console) 2>&1
        export XMX=2625m
        export JAVA_OPTS=
        export DATOMIC_DEPLOY_BUCKET=deploy-a0dbc565-faf2-4760-9b7e-29a8e45f428e
        export DATOMIC_VERSION=0.9.5656
        cd \/datomic 
        cat <<EOF >aws.properties 
        host=`curl http:\/\/169.254.169.254\/latest\/meta-data\/local-ipv4`
        alt-host=`curl http:\/\/169.254.169.254\/latest\/meta-data\/public-ipv4
        aws-dynamodb-region=us-east-1\naws-transactor-role=datomic-aws-transactor\naws-peer-role=datomic-aws-peer\nprotocol=ddb\nmemory-index-max=256m\nport=4334\nmemory-index-threshold=32m\nobject-cache-max=128m\nlicense-key=hvx\/HkWObCoC2iAesriLRFV1\/nC1y4zlFqaNuH0LWsAtDiQbtCFZcCNQwJPEcu9oJmP7w\/f6GxXUQ7JqSB6iU74Azn6nCupeQUxNbzCQXpir+8MOo57K+FPF1+ExLCfOdwjQtdyXlSxPJ8Vmf4coqoD0k32yRhWnuR2Zk70zAyR85wL+5I\/n0jjDKIph+JGD2vVzy+C2Nfq8wokTiLma\/CrkTL9uIO4LjT8ZbRwFcOeVhht9HgTM9wclOG1kFz9VLnEhn4gX6JdWVlOKXH2cjzww+eGAIQtPYkeB1ZL00F5hMWaM8zux5pfmmBCM+kJ5cqntwn33dpqfRL\/4NC1SDw==\naws-dynamodb-table=your-system-name
        EOF
        chmod 744 aws.properties
        aws s3 cp \"s3:\/\/${DATOMIC_DEPLOY_BUCKET}\/${DATOMIC_VERSION}\/startup.sh\" startup.sh
        chmod 500 startup.sh
        .\/startup.sh 
        
  AppNodeSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: To allow ssh and http
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0